# Generated by Django 4.2.13 on 2026-02-02 21:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_number', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('account_type', models.CharField(choices=[('Savings', 'Savings'), ('Current', 'Current'), ('Fixed', 'Fixed'), ('Joint', 'Joint'), ('Corporate', 'Corporate')], default='Savings', max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('date_opened', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Dormant', 'Dormant'), ('Suspended', 'Suspended')], default='Active', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(choices=[('Mr', 'Mr.'), ('Mrs', 'Mrs.'), ('Ms', 'Ms.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.'), ('Rev.', 'Rev.')], default='Mr', max_length=5)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('tax_number', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('po_box', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal'), ('Transfer', 'Transfer'), ('Payment', 'Payment')], default='Deposit', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('served_by', models.CharField(max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.account')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('loan_type', models.CharField(choices=[('Emergency', 'Emergency'), ('Education', 'Education'), ('Personal', 'Personal'), ('Development', 'Development')], default='Personal', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_status', models.CharField(choices=[('Approved', 'Approved'), ('Disbursed', 'Disbursed'), ('Active', 'Active'), ('Closed', 'Closed')], default='Approved', max_length=50)),
                ('date_approved', models.DateField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.account')),
            ],
            options={
                'ordering': ['-date_approved'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
    ]
