# Generated by Django 4.2.13 on 2026-02-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_salutation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Dormant', 'Dormant'), ('Suspended', 'Suspended'), ('Pending', 'Pending')], default='Active', max_length=20),
        ),
    ]
