# Generated by Django 4.2.13 on 2026-02-03 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loantransaction',
            name='is_reversal',
        ),
        migrations.RemoveField(
            model_name='loantransaction',
            name='reversed_transaction',
        ),
    ]
